### ISSUE TITLE
[BUG]: All icons are missing in v4.8.2

### ISSUE THREAD

**Issue by Mitecon** [martinrotter/rssguard#1683]
### Brief description of the issue

I'm using the appimage version on KDE.

In v4.8.2, all icons are missing. This is icons for feeds and the coloured circles for labels. When I switch back to v4.8.1, all of these icons are back again.

It's not until moments like these that I realise just how much I rely on visual clues that icons and/or colours provide. It's so distracting and slows me down so much I've reverted to v4.8.1 for now.

### How to reproduce the bug?

Literally switching back and forth between the two versions makes this problem appear and disappear.

### What was the expected result?

The icons appear, like so:

![Image](https://github.com/user-attachments/assets/36b20614-c03f-4aec-a560-949a0f30cf4d)

![Image](https://github.com/user-attachments/assets/4defaa5f-b988-4374-9a00-b722b5722af4)

### What actually happened?

The icons don't appear, like so:

![Image](https://github.com/user-attachments/assets/a6e523b3-38d7-4235-89fd-0723f60cf4a8)

![Image](https://github.com/user-attachments/assets/6e20cb0e-158a-41c5-8fca-201e74e1f5f4)

### Debug log

The logs I've provided contain: Starting the appimages from the terminal, waiting for the icon to appear on the taskbar, clicking the icon to make RSS Guard fullscreen, then exiting it.

[v4.8.1.log](https://github.com/user-attachments/files/19573247/v4.8.1.log)

[v4.8.2.log](https://github.com/user-attachments/files/19573249/v4.8.2.log)

### Operating system and version

Operating System: EndeavourOS 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.3
Kernel Version: 6.12.21-1-lts (64-bit)
Graphics Platform: X11

**Comment by martinrotter** [comment]
Already fixed with https://github.com/martinrotter/rssguard/commit/dcd71c2573db639087b1e9793b8a4163b5d6d423

**Comment by martinrotter** [comment]
Yes, the other user reported this on Discord, nevermind.

**Comment by nullproblemo** [comment]
The same problem still exists with rssguardlite 4.8.2 (flatpak).: All icons are lost.

**Comment by nullproblemo** [comment]
I just updated to version 4.8.3. The icons are back again. Thanks!

**Comment by chrisretusn** [comment]
I "had" the issue also, issued fixed. Thanks!
