### ISSUE TITLE
Internal web browser unreadable on HiDPI screen

### ISSUE THREAD

**Issue by gromain** [martinrotter/rssguard#221]
#### Brief description of the issue.

When using the application on a computer with a HiDPI screen, web browser content is unreadable.

#### How to reproduce the bug?

1. Use a HIDPI screen 
2. Open the application

#### What is the expected result?

Readable text

#### What actually happened?

Tiny tiny tiny text,  to the point of unreadability

#### Other information (logs, see Wiki)

I'm running Manjaro with KDE Plasma 5 on a Dell XPS 9570.

**Comment by martinrotter** [comment]
Try latest dev version and let me know if there is any difference.

**Comment by gromain** [comment]
Hi,

Still no dice! Latest version compiled from source (with version from commit e1949c8628133e9d60f4c7cb23a91f1235be7fcc) with `qmake $srcdir/$_pkgname/build.pro CONFIG+=debug INSTALL_ROOT=$pkgdir PREFIX=/usr` (I'm building from the Arch User Repository, hence the strange syntax) still looks like this:

![image](https://user-images.githubusercontent.com/2188885/79738000-74225d00-82fc-11ea-8a8d-8f2d6dfefac5.png)

Latest AppImage development version for Linux crashes when I open content from a feed.

If there is anything I can do to help debug, let me know!

**Comment by martinrotter** [comment]
Yes, there was old regression when moving from QtWebkit to QtWebEngine. I fixed and now when web viewer has focus it responds to "zoom" shortcuts (mouse wheel + ctrl, or +-/ctrl) and this zoom is afterwards persistently saved and loaded when rssguard is next launched.

Try latest dev version and let me know.

**Comment by martinrotter** [comment]
9acef04a

**Comment by gromain** [comment]
Thanks for the fix. It's still not working for me as I can't zoom with my touchpad for some reason. I'll test with a mouse and report if something is still broken but there should be no further problem!
I tested with the version compiled from commit d78c654293b95b5fbf423a81192d868e542dd62f and the AppImage testing build.

Once again, thanks a lot for the fix and your work on rssguard! I really appreciate it!

**Comment by gromain** [comment]
OK, I tested again and it worked. Still not sure what was wrong with my touchpad, but it clearly was on my side!

Thanks again, stay safe mate!

**Comment by martinrotter** [comment]
Well, there is some history regarding touchpad "zooming" and Qt library, which is used by RSS Guard as GUI component.

I would bet that your touchpad is actually not the problem and Qt is the real problem.
